home:
    path: /
    controller: App\UI\Controller\MainPage\Controller

paste_create:
    path: /paste/create
    controller: App\UI\Controller\Paste\Create\Controller

paste_show_one:
    path: /paste/{hash}
    controller: App\UI\Controller\Paste\ShowOne\Controller